server:
  port: 8089
  

spring:
  application:
    name: API-GATEWAY-MICROSERVICE
    
  cloud:
    gateway:
      routes:
        - id: USER_SERVICE_MICROSERVICE
          uri: lb://USER_SERVICE_MICROSERVICE
          predicates:
            - Path=/users/**
            
        - id: HOTEL_SERVICE_MICROSERVICE
          uri: lb://HOTEL_SERVICE_MICROSERVICE
          predicates:
            - Path=/hotels/**
         
            
        - id: RATING_SERVICE_MICROSERVICE
          uri: lb://RATING_SERVICE_MICROSERVICE
          predicates:
            - Path=/ratings/**
        
        
            
            

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

      
  
